image: 941618104661.dkr.ecr.us-east-1.amazonaws.com/jmeter-plugins-build:3.2

build:
  stage: build
  tags:
    - docker
  except:
    - master
  script:
    - mvn -e -X clean install
  artifacts:
    paths:
      - target/jmeter-bzm-http2-*.jar
      - target/surefire-reports
    expire_in: 1 month