image: 941618104661.dkr.ecr.us-east-1.amazonaws.com/jmeter-plugins-build:3.3

build:
  stage: build
  tags:
    - docker
  except:
    - master
  script:
    - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    - mvn -e -X clean install
  artifacts:
    paths:
      - target/jmeter-bzm-http2-*.jar
      - target/failsafe-reports
      - target/surefire-reports
    expire_in: 1 month
release:
  stage: deploy
  tags:
    - docker
  only:
    - master
  when: manual
  script: /release.sh
  artifacts:
    paths:
      - target/jmeter-bzm-http2-*.jar
