language: java
dist: trusty
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"

before_deploy:
  - mvn --batch-mode versions:set -DnewVersion="$(T=${TRAVIS_TAG%%-lib}; echo ${T:1})"
  - mvn clean package -DskipTests

deploy: 
  provider: releases
  api_key: 
    secure: efba9b319cc0a224417596be78725e39cc322f71
    file_glob: true
    file: target/jmeter-bzm-http2-*.jar
    skip_cleanup: true
    on:
      tags: true
      repo: Blazemeter/jmeter-http2-plugin

